//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccentureAccademyLibrary.GonzaloIriart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WrittenBy
    {
        public int Id { get; set; }
        public int Id_Book { get; set; }
        public int id_Author { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Book Book { get; set; }
    }
}
